services:
    mysql:
        image: mysql:latest
        container_name: container_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: DStore
            MYSQL_USER: hoangdai
            MYSQL_PASSWORD: hd123  
        ports:
            - "3307:3306"
    # volumes:
    #     - mysql-data:/var/lib/mysql
    dstore.com:
        container_name: go_backend_dstore
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            APP_NAME: "DStore"
            DB_CONN_STR: "root:123@tcp(mysql:3306)/DStore?charset=utf8mb4&parseTime=True&loc=Local"
            JWT_SECRET: "099a0fa5-d9c6-4d6a-bf04-faf39e16e75b"
            JWT_EXPIRES_IN: "12d"
            SYSTEM_ACCOUNT: "system"
            SYSTEM_PW: "systempw"
        restart: always
        depends_on:
            - mysql
        ports:
            - "8099:8069"    
    


